### PR TITLE
chore: Update radix components and fix portal preview issue

### LINKED ISSUE #771: Update Radix components
Several bugfixes have been released for Radix components since they were installed.

### PR DESCRIPTION
**Pull request by knagurski**
fixes #771

### CODE REVIEW

File: packages/ui/tailwind.ts [hunk 1]
```diff
@@ -315,23 +315,23 @@ export default {
...
+          'radial-gradient(50% 50% at 50% 50%, hsla(var(--canary-nav-item-gradient-1)) 0%, hsla(var(--canary-nav-item-gradient-2)) 17.63%, hsla(var(--canary-nav-item-gradient-3)) 40.23%, hsla(var(--canary-nav-item-gradient-4)) 61.54%, hsla(var(--canary-nav-item-gradient-5)) 80%, hsla(var(--canary-nav-item-gradient-6)) 100%)'
       },
       keyframes: {
         'accordion-down': {
           from: { height: '0' },
-          to: { height: 'var(--canary-radix-accordion-content-height)' }
+          to: { height: 'var(--radix-accordion-content-height)' }
         },
         'accordion-up': {
-          from: { height: 'var(--canary-radix-accordion-content-height)' },
```
Comment (knagurski) [inline packages/ui/tailwind.ts:334]: This were mistakenly prefixed previously. The values come from the component itself, not global custom properties.

File: packages/ui/package.json [hunk 2]
```diff
@@ -55,34 +55,34 @@
...
-    "@radix-ui/react-separator": "^1.1.0",
-    "@radix-ui/react-slider": "^1.2.0",
-    "@radix-ui/react-slot": "^1.1.0",
-    "@radix-ui/react-switch": "^1.1.0",
-    "@radix-ui/react-tabs": "^1.1.0",
-    "@radix-ui/react-toast": "^1.2.1",
-    "@radix-ui/react-toggle": "^1.1.0",
-    "@radix-ui/react-toggle-group": "^1.1.0",
-    "@radix-ui/react-tooltip": "^1.1.1",
+    "@radix-ui/react-accordion": "^1.2.2",
```
Comment (c-joetaylor-harness) [inline packages/ui/package.json:58]: Can we be sure that updating these will not produce unexpected results in existing components? 

If so, approved.

**Review by c-joetaylor-harness — APPROVED** [review]

File: packages/ui/package.json (hunk 2 above)
Comment (knagurski) [reply packages/ui/package.json:58]: Since we have no tests or any safety nets, all we can do is a visual click-through and trust that the Radix devs followed SemVer properly (which they seem to do). I didn't notice any issues personally.

Comment (c-joetaylor-harness) [reply packages/ui/package.json:58]: This is why we need tests 

cc @abhinavrastogi-harness
